import type { SceneGraph } from "@story-maker/scene-schema";

export const MOCK_PREVIEW_SCENES: SceneGraph[] = [
  {
    id: "intro-scene",
    pageNumber: 1,
    width: 960,
    height: 540,
    backgroundColor: "#dbeafe",
    layers: [
      {
        id: "intro-background",
        kind: "background",
        name: "Sunny meadow",
        sourceUrl: "/assets/background-intro.svg",
        x: 0,
        y: 0,
        width: 960,
        height: 540,
      },
      {
        id: "pig-pink",
        kind: "sprite",
        name: "Pink pig",
        sourceUrl: "/assets/character-pig-pink.svg",
        x: 190,
        y: 260,
        width: 150,
        height: 170,
      },
      {
        id: "pig-baby",
        kind: "sprite",
        name: "Baby pig",
        sourceUrl: "/assets/character-pig-baby.svg",
        x: 405,
        y: 245,
        width: 145,
        height: 175,
      },
      {
        id: "pig-black",
        kind: "sprite",
        name: "Black pig",
        sourceUrl: "/assets/character-pig-black.svg",
        x: 625,
        y: 250,
        width: 150,
        height: 170,
      },
    ],
    template: {
      type: "stagger_pop_in",
      trigger: "tap",
      sequence: [
        { layerId: "pig-pink", delayMs: 0 },
        { layerId: "pig-baby", delayMs: 220 },
        { layerId: "pig-black", delayMs: 440 },
      ],
    },
    updatedAt: "2026-06-08T00:00:00.000Z",
  },
  {
    id: "house-scene",
    pageNumber: 2,
    width: 960,
    height: 540,
    backgroundColor: "#fef3c7",
    layers: [
      {
        id: "house-background",
        kind: "background",
        name: "House building site",
        sourceUrl: "/assets/background-house.svg",
        x: 0,
        y: 0,
        width: 960,
        height: 540,
      },
      {
        id: "hammer-sequence",
        kind: "sprite_sequence",
        name: "Black pig hammering",
        frames: [
          "/assets/frame-hammer-0.svg",
          "/assets/frame-hammer-1.svg",
          "/assets/frame-hammer-2.svg",
          "/assets/frame-hammer-3.svg",
        ],
        fps: 6,
        loop: true,
        x: 360,
        y: 235,
        width: 220,
        height: 220,
      },
    ],
    updatedAt: "2026-06-08T00:00:00.000Z",
  },
];
